[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

lib_deps =
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit GFX Library @ ^1.12.6
    https://github.com/jaretburkett/ILI9488.git#master
